// File automatically generated by swift-bridge.
typedef struct PuzzleError PuzzleError;
void __swift_bridge__$PuzzleError$_free(void* self);

void* __swift_bridge__$Vec_PuzzleError$new(void);
void __swift_bridge__$Vec_PuzzleError$drop(void* vec_ptr);
void __swift_bridge__$Vec_PuzzleError$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_PuzzleError$pop(void* vec_ptr);
void* __swift_bridge__$Vec_PuzzleError$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_PuzzleError$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_PuzzleError$len(void* vec_ptr);
void* __swift_bridge__$Vec_PuzzleError$as_ptr(void* vec_ptr);

typedef struct Alg Alg;
void __swift_bridge__$Alg$_free(void* self);

void* __swift_bridge__$Vec_Alg$new(void);
void __swift_bridge__$Vec_Alg$drop(void* vec_ptr);
void __swift_bridge__$Vec_Alg$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_Alg$pop(void* vec_ptr);
void* __swift_bridge__$Vec_Alg$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_Alg$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_Alg$len(void* vec_ptr);
void* __swift_bridge__$Vec_Alg$as_ptr(void* vec_ptr);

typedef struct Event Event;
void __swift_bridge__$Event$_free(void* self);

void* __swift_bridge__$Vec_Event$new(void);
void __swift_bridge__$Vec_Event$drop(void* vec_ptr);
void __swift_bridge__$Vec_Event$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_Event$pop(void* vec_ptr);
void* __swift_bridge__$Vec_Event$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_Event$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_Event$len(void* vec_ptr);
void* __swift_bridge__$Vec_Event$as_ptr(void* vec_ptr);

struct __private__ResultPtrAndPtr __swift_bridge__$random_scramble_for_event(void* event);


