name: Create xcframework
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build xcframework
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - run: rustup toolchain install nightly --profile minimal
      - run: rustup component add rust-src --toolchain nightly-x86_64-apple-darwin
      - run: script/build-swift-package
      - run: tar cvzf TWSearch.xcframework.tar.gz TWSearch.xcframework
      - uses: svenstaro/upload-release-action@v2
        with:
           
