name: GitHub Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Release version'

jobs:
  build_and_publish:
    name: Build xcframework
    permissions:
      contents: write
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - run: rustup toolchain install nightly --profile minimal
      - run: rustup component add rust-src --toolchain nightly-x86_64-apple-darwin
      - run: script/build-swift-package
      - run: tar cvzf TWSearch.xcframework.tar.gz TWSearch.xcframework
      - name: Update Package.Swift
        run: |
            echo test "$(sha256sum TWSearch.xcframework.tar.gz)" >> test
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add test
            git commit -a -m "Update Package.Swift"
            git tag -a -m "Release ${{ github.event.inputs.version }}" "${{ github.event.inputs.version }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Calculate release body
        run: |
            # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string
            EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
            echo "RELEASE_BODY<<$EOF" >> $GITHUB_ENV
            git log --format=%b -n 1 HEAD >> $GITHUB_ENV
            echo "$EOF" >> $GITHUB_ENV
      - name: Publish release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ github.event.inputs.version }}"
          release_name: "TWSearch release ${{ github.event.inputs.version }}"
          body: ${{ env.RELEASE_BODY }}
          draft: false
          prerelease: false
